# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('cinema', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('datetime', models.DateTimeField()),
                ('age', models.CharField(max_length=5)),
            ],
        ),
    ]
