# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField()),
                ('time', models.CharField(max_length=5)),
                ('age', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
