# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20171124_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
